version: '3.2'

services:
  poc-google-auth:
    container_name: poc-google-auth
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./application:/app
    ports:
      - "8000:8000"
    entrypoint: php -S 0.0.0.0:8000 -t /app